[local]
localhost

[mongodb]
mongodb-dev.daws88.site

[catalogue]
catalogue-dev.daws88.site

[redis]
redis-dev.daws88.site

[user]
user-dev.daws88.site

[cart]
cart-dev.daws88.site

[mysql]
mysql-dev.daws88.site

[shipping]
shipping-dev.daws88.site

[rabbitmq]
rabbitmq-dev.daws88.site

[payment]
payment-dev.daws88.site

[frontend]
frontend-dev.daws88.site